#!/usr/bin/env python3
"""Builds the Turkish 5-letter word lists from hunspell-tr (https://github.com/tdd-ai/hunspell-tr).

Usage:
    git clone https://github.com/tdd-ai/hunspell-tr
    python tools/wordlists/build_tr.py path/to/hunspell-tr [--candidates review.txt]

Outputs (one lowercase word per line, `#` lines are comments, see WordList.parseLines):
    shared/src/commonMain/composeResources/files/words/tr_valid.txt    every accepted guess
    shared/src/commonMain/composeResources/files/words/tr_answers.txt  pool for the endless feed

How hunspell-tr is stored: tr_TR.dic holds stems, each followed by flags (`stem/12,345,...`), and
tr_TR.aff maps every flag to exactly one suffix (`SFX <flag> 0 <suffix> .`: nothing is stripped, the
condition is always `.`). So the inflected forms of a stem are simply stem + suffix, and a five-letter
form needs len(stem) + len(suffix) == 5. We never have to expand the full dictionary (millions of forms).

- valid   = every five-letter form (stems that are already five letters, plus stem + suffix), only
            letters of the Turkish alphabet. This is the dictionary, so it is as noisy as hunspell-tr.
- answers = tools/wordlists/tr_answers_curated.txt: reviewed by hand (common base words, no proper nouns,
            nothing offensive). Every entry must be in `valid`, the script fails otherwise.
- --candidates writes the five-letter stems that are not obviously inflections, the input for that review.
"""
import argparse
import os
import subprocess
import sys

TR_ALPHABET = set("abcçdefgğhıijklmnoöprsştuüvyz")
HERE = os.path.dirname(__file__)
CURATED = os.path.join(HERE, "tr_answers_curated.txt")
OUT_DIR = os.path.join(HERE, "..", "..", "shared", "src", "commonMain", "composeResources", "files", "words")


def read_suffixes(aff_path):
    suffixes = {}
    with open(aff_path, encoding="utf-8") as f:
        for line in f:
            p = line.split()
            if len(p) == 5 and p[0] == "SFX":
                assert p[2] == "0" and p[4] == ".", f"unexpected rule shape: {line!r}"
                suffixes[p[1]] = p[3]
    return suffixes


def expand(dic_path, suffixes):
    """Returns (valid five-letter forms, five-letter stems)."""
    forms, stems5 = set(), set()
    with open(dic_path, encoding="utf-8") as f:
        next(f)  # first line is the entry count
        for line in f:
            stem, _, flags = line.strip().partition("/")
            if len(stem) == 5:
                forms.add(stem)
                stems5.add(stem)
            elif len(stem) < 5 and flags:
                need = 5 - len(stem)
                forms.update(stem + suffixes[fl] for fl in flags.split(",") if len(suffixes[fl]) == need)
    return {w for w in forms if all(c in TR_ALPHABET for c in w)}, stems5


def main():
    ap = argparse.ArgumentParser(description="Build Turkish word lists from hunspell-tr")
    ap.add_argument("root", help="path to a hunspell-tr checkout")
    ap.add_argument("--candidates", help="also write the answer review candidates to this file")
    args = ap.parse_args()

    commit = subprocess.run(["git", "-C", args.root, "rev-parse", "HEAD"], capture_output=True,
                            text=True, check=True).stdout.strip()
    suffixes = read_suffixes(os.path.join(args.root, "tr_TR.aff"))
    valid, stems5 = expand(os.path.join(args.root, "tr_TR.dic"), suffixes)

    with open(CURATED, encoding="utf-8") as f:
        answers = sorted({w.strip() for w in f if w.strip() and not w.startswith("#")})
    wrong_length = [w for w in answers if len(w) != 5]
    if wrong_length:
        sys.exit(f"curated answers that are not five letters: {wrong_length}")
    missing = [w for w in answers if w not in valid]
    if missing:
        sys.exit(f"curated answers missing from the valid set: {missing[:20]}")

    if args.candidates:
        candidates = sorted(w for w in stems5 if w in valid)
        with open(args.candidates, "w", encoding="utf-8", newline="\n") as f:
            f.write("".join(w + "\n" for w in candidates))
        print(f"candidates={len(candidates)} -> {args.candidates}")

    os.makedirs(OUT_DIR, exist_ok=True)
    notice = (f"# Generated by tools/wordlists/build_tr.py from hunspell-tr commit {commit}\n"
              "# Source: https://github.com/tdd-ai/hunspell-tr (MPL-2.0, see THIRD_PARTY_NOTICES.md). Do not edit by hand.\n")
    with open(os.path.join(OUT_DIR, "tr_valid.txt"), "w", encoding="utf-8", newline="\n") as f:
        f.write(notice + "".join(w + "\n" for w in sorted(valid)))
    own = ("# Generated by tools/wordlists/build_tr.py from tools/wordlists/tr_answers_curated.txt\n"
           "# Hand-reviewed answer pool (MIT, BrainScroll's own work). Do not edit by hand.\n")
    with open(os.path.join(OUT_DIR, "tr_answers.txt"), "w", encoding="utf-8", newline="\n") as f:
        f.write(own + "".join(w + "\n" for w in answers))
    print(f"valid={len(valid)} answers={len(answers)}")


if __name__ == "__main__":
    main()
