#!/usr/bin/env python3
"""Builds the English 5-letter word lists from SCOWL v2 (https://github.com/en-wl/wordlist).

Usage:
    git clone https://github.com/en-wl/wordlist scowl
    (cd scowl && PYTHONUTF8=1 python combine.py create-db scowl.db)
    python tools/wordlists/build_en.py path/to/scowl

Outputs (one lowercase word per line, `#` lines are comments, see WordList.parseLines):
    shared/src/commonMain/composeResources/files/words/en_valid.txt    every accepted guess
    shared/src/commonMain/composeResources/files/words/en_answers.txt  pool for the endless feed

Rules:
- American spelling, accents stripped, only plain a-z (drops proper nouns, acronyms, apostrophes).
- valid   = SCOWL size <= 80 ("a valid word in current usage").
- answers = SCOWL size <= 35 minus: vulgar/offensive words (SCOWL usage notes), roman numerals,
            plain inflections (plurals / past tense whose stem is itself a valid word),
            and the hand-reviewed words in tools/wordlists/blocklist_en.txt.
"""
import os
import re
import subprocess
import sys

VALID_SIZE = 80
ANSWER_SIZE = 35
FIVE = re.compile(r"^[a-z]{5}$")
ROMAN = re.compile(r"^[ivxlcdm]+$")
NOSUGGEST = "vulgar-1,vulgar-2,vulgar-3,offensive-1,offensive-2,offensive-3"
BLOCKLIST = os.path.join(os.path.dirname(__file__), "blocklist_en.txt")
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "shared", "src", "commonMain",
                       "composeResources", "files", "words")


def scowl(root, size, *extra):
    env = dict(os.environ, PYTHONUTF8="1")
    out = subprocess.run(
        [sys.executable, os.path.join(root, "scowl"), "--db", os.path.join(root, "scowl.db"),
         "word-list", str(size), "A", "1", "--deaccent", *extra],
        capture_output=True, text=True, encoding="utf-8", env=env, check=True)
    return out.stdout.splitlines()


def five_letter(lines):
    return {w for w in lines if FIVE.match(w)}


def is_inflection(word, known):
    if word.endswith("eed"):  # seed, need, feed: the stem is a different word
        return False
    if word.endswith("s") and not word.endswith("ss"):
        return word[:-1] in known or word[:-2] in known or (word.endswith("ies") and word[:-3] + "y" in known)
    if word.endswith("ed"):
        return word[:-1] in known or word[:-2] in known
    return False


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    root = sys.argv[1]
    commit = subprocess.run(["git", "-C", root, "rev-parse", "HEAD"], capture_output=True,
                            text=True, check=True).stdout.strip()

    every_word = set(scowl(root, VALID_SIZE))  # all lengths: stems of 5-letter inflections are shorter
    valid = five_letter(every_word)
    # With --nosuggest, flagged words come back with a "/!" suffix instead of being removed.
    flagged = {w[:-2] for w in scowl(root, VALID_SIZE, "--nosuggest", NOSUGGEST) if w.endswith("/!")}
    with open(BLOCKLIST, encoding="utf-8") as f:
        blocked = {w.strip() for w in f if w.strip() and not w.startswith("#")}
    small = five_letter(scowl(root, ANSWER_SIZE))
    answers = {w for w in small
               if w in valid and w not in flagged and w not in blocked and not ROMAN.match(w) and not is_inflection(w, every_word)}

    os.makedirs(OUT_DIR, exist_ok=True)
    header = (f"# Generated by tools/wordlists/build_en.py from SCOWL v2 commit {commit}\n"
              "# Source: https://github.com/en-wl/wordlist (see THIRD_PARTY_NOTICES.md). Do not edit by hand.\n")
    for name, words in (("en_valid.txt", valid), ("en_answers.txt", answers)):
        with open(os.path.join(OUT_DIR, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(header + "".join(w + "\n" for w in sorted(words)))
    print(f"valid={len(valid)} answers={len(answers)} flagged5={len(flagged & valid)} "
          f"(small={len(small)}, removed={len(small) - len(answers)})")


if __name__ == "__main__":
    main()
